ALTER TABLE template ADD COLUMN bind_type TEXT;
  ALTER TABLE template ADD COLUMN volume FLOAT;
  ALTER TABLE template ADD COLUMN weight FLOAT;
  ALTER TABLE template ADD COLUMN damage_per_turn FLOAT;
  ALTER TABLE template ADD COLUMN damage_shape TEXT;
  ALTER TABLE template ADD COLUMN damage_type TEXT;
  ALTER TABLE template ADD COLUMN slot TEXT;
  ALTER TABLE template ADD COLUMN swing_duration BIGINT;
  ALTER TABLE template ADD COLUMN ready_time BIGINT;
